# Generated by Django 5.1.6 on 2025-04-27 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_learn', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='films',
            new_name='Film',
        ),
    ]
