version: "3.8"

services:
  web:
    build: .
    container_name: django_app

    volumes:
      - .:/app

    expose: 
      - "8000"

  nginx:
    build: 
      context: ./nginx
    container_name: nginx

    ports:
      - "80:80"

    depends_on:
      - web
